### PR TITLE
Code style

### PR DESCRIPTION
**Pull request by grogy**
Hello,

it contains refactoring for better code style. The functions are not changed.

### CODE REVIEW

**Comment by ollie** [comment]
Hello, looking good. If I remember correctly, we can also change `NULL` to `null` for consistency. Could you look into that too? Thanks!

**Comment by grogy** [comment]
In code is used `NULL` often. For it I [uppercase language constants](https://github.com/fakturoid/fakturoid-php/pull/16/commits/5309061fdd339cfbbcc34cbaafd1f3de10fd9902).

So what style we use - `true` / `false` / `null` or `TRUE` / `FALSE` / `NULL`?

**Comment by ollie** [comment]
Sorry for the delay, too many things to do. Anyway I'd follow the PSR-2 guide which says language keywords should be lowercased http://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull.

**Comment by grogy** [comment]
Thank you, I changed it.

**Comment by ollie** [comment]
There were other things I wanted to do so I decided to make those changes from scratch. But thanks for the effort and suggestions, it was needed. 😺

I mentioned you in the last commit https://github.com/fakturoid/fakturoid-php/commit/7bd75c647a5c3d6d6257dacaccf93618a06544d2 to give credits.

**Pull request closed without merging**
