### PR TITLE
New feature in 'run' method – using 'If-Modified-Since', Typo and PHPDoc

### PR DESCRIPTION
**Pull request by tomaskavalek**

### CODE REVIEW

**Comment by ollie** [comment]
Hello, I just pushed code style fixes which are as close to PSR-2 as possible without breaking API compatibility. We will look at `If-Modified-Since` and PHPDoc annotations some time in January (too many things going on now), we will probably want to document them themselves but we will give you credit for the idea.

By the way you shouldn't really do a lot of changes and commit them at once – it's very hard to see the individual changes.

I'll leave the PR open so I won't forget.

**Comment by tomaskavalek** [comment]
Lot of changes in commit, that’s true. I didn’t know about your prepairing of PSR-2.

The major change - feature - is `If-Modified-Since`, which you recommend at API DOC.

But I fully understand, it’s in your hands 😀

**Comment by ollie** [comment]
This repo has been neglected for some time and needs some love, your PR and the other PR just made me sit down and do it. There are a few more things we'd like to do so once we have some solid tests and versioning in place, things can get moving more rapidly (and safely).

**Comment by ollie** [comment]
Heya, I've pushed a new version (tagged 1.0.0) which includes the headers update. It was a backwards-incompatible change so we cleaned up the repo a bit as well (please consult CHANGELOG.md for upgrading). Also let us know if we managed to break anything. :-)

**Pull request closed without merging**
